### ISSUE TITLE
integrating with Gphoto2?

### ISSUE THREAD

**Issue by Blueshawk** [asalamon74/pktriggercord#21]
@asalamon74  I have been admiring your work for a long time as I try to set up a remote observatory using my pentax k-50 as the main camera for an Indi/ekos setup. Unfortunately, like many Linux tethering apps, the Indilib drivers use libGphoto2, which in turn uses the outdated Pktether to talk to early pentax cameras and doesn't support the later ones. I approached Gphoto developer @msmeissn but he has his hands full over there with other projects. I've been comparing code between the two and I think reintegrating the much improved pktriggercord to Gphoto would help get the k series tethered in many apps at once. Maybe you guys can get together sometime and being familiar with the code, you might bang something out fairly easily. 

https://github.com/gphoto/libgphoto2

 I'll be glad to help test with my k-50 as time allows. I currently have both programs compiling from current git on my xubuntu (15.10) box as well as my recently updated notebook running xubuntu 16.10

Meanwhile I think I'll poke at that k-50 bulbing problem a bit, it seems more up my street as a repair tech.

**Comment by msmeissn** [comment]
I worked a bit on a longer train ride. I think there is similar to the previous pslr port an easy way

- use several pslr* files directly 1:1
- wrapper library.c file that  offers the libgphoto2 driver interface

**Comment by asalamon74** [comment]
I think libgphoto2 uses pkremote and not pktether. Pktether is a closed source application, pkremote is the original pentax tethering project I've forked to create pktriggercord.

Integration is OK for me, but I don't plan to modify my code too much. I don't like to idea to add lots of gphoto-specific code to pktriggercord. 

I'll check the pull request soon.

**Comment by msmeissn** [comment]
i need to redo it, i was a bit too enthusiastic with the windows part, and travis fails on win32

**Comment by asalamon74** [comment]
@msmeissn Yes, I've also realized that. You can check windows compilation using make localwin, that will also download the crosscompiler.

**Comment by asalamon74** [comment]
I close this issue, because it's more like an issue for libgphoto2 and not for pktriggercord.

**Comment by ian-morgan99** [comment]
On this topic, I have raised the question here to ask the makers of libgphoto2 to update their project to reference these libraries, instead of the PKRemote ones, which seem to be badly out of date now. 

I hope that's OK. 

I know this issue was closed, but if there are any clues that can be shared here of what they need to do, it would be greatly appreciated.   Here's the link :   https://github.com/gphoto/libgphoto2/issues/928

**Comment by msmeissn** [comment]
commit 3118a779151d9b39b907a2b2817929011b0a9bd3

again, we still need the USB ids of the K3-III and K1-II

**Comment by ian-morgan99** [comment]
Thanks for your quick reply.
How do I find those USB id's ? I have both bodies here.
Cheers,
Ian.

**Comment by asalamon74** [comment]
I usually find the ids here: https://exiftool.org/TagNames/Pentax.html

**Comment by ian-morgan99** [comment]
> commit 3118a779151d9b39b907a2b2817929011b0a9bd3
> 
> again, we still need the USB ids of the K3-III and K1-II

I think I now have them. When I attach the K3iii camera in MSC mode, I get the following in the event log. 

I assume you need either:
USB\VID_25FB&PID_0189\8093033

Or maybe:
Vendor IDs:	
		USB\VID_25FB&PID_0189&REV_0200
		USB\VID_25FB&PID_0189
-----------------------------------------------------------------------

I'll now see if I can get the same for the K1ii


A new external device was recognized by the system.

Subject:
	Security ID:		SYSTEM
	Account Name:		**************$
	Account Domain:		WORKGROUP
	Logon ID:		0x3E7

Device ID:	USB\VID_25FB&PID_0189\8093033

Device Name:	PENTAX K-3 Mark III

Class ID:		{eec5ad98-8080-425f-922a-dabf3de3f69a}

Class Name:	WPD

Vendor IDs:	
		USB\VID_25FB&PID_0189&REV_0200
		USB\VID_25FB&PID_0189
		
		

Compatible IDs:	
		USB\COMPAT_VID_25FB&Class_06&SubClass_01&Prot_01
		USB\COMPAT_VID_25FB&Class_06&SubClass_01
		USB\COMPAT_VID_25FB&Class_06
		USB\Class_06&SubClass_01&Prot_01
		USB\Class_06&SubClass_01
		USB\Class_06
		
		

Location Information:	
		Port_#0001.Hub_#0002

**Comment by ian-morgan99** [comment]
The Pentax K1ii gives :

A new external device was recognized by the system.

Subject:
	Security ID:		SYSTEM
	Account Name:		DESKTOP-B595CK8$
	Account Domain:		WORKGROUP
	Logon ID:		0x3E7

Device ID:	USBSTOR\Disk&Ven_RICOHIMG&Prod_DSC_K-1_Mark_II&Rev_1.02\7371227&0

Device Name:	RICOHIMG DSC_K-1_Mark_II USB Device

Class ID:		{4d36e967-e325-11ce-bfc1-08002be10318}

Class Name:	DiskDrive

Vendor IDs:	
		USBSTOR\DiskRICOHIMGDSC_K-1_Mark_II_1.02
		USBSTOR\DiskRICOHIMGDSC_K-1_Mark_II_
		USBSTOR\DiskRICOHIMG
		USBSTOR\RICOHIMGDSC_K-1_Mark_II_1
		RICOHIMGDSC_K-1_Mark_II_1
		USBSTOR\GenDisk
		GenDisk
		
		

Compatible IDs:	
		USBSTOR\Disk
		USBSTOR\RAW
		GenDisk
		
		

Location Information:

**Comment by ian-morgan99** [comment]
Or maybe this is what you need (K1ii in MSC mode):

A new external device was recognized by the system.

Subject:
	Security ID:		SYSTEM
	Account Name:		DESKTOP-****$
	Account Domain:		WORKGROUP
	Logon ID:		0x3E7

Device ID:	USB\VID_25FB&PID_0182\7371227

Device Name:	USB Mass Storage Device

Class ID:		{36fc9e60-c465-11cf-8056-444553540000}

Class Name:	USB

Vendor IDs:	
		USB\VID_25FB&PID_0182&REV_0102
		USB\VID_25FB&PID_0182
		
		

Compatible IDs:	
		USB\COMPAT_VID_25FB&Class_08&SubClass_06&Prot_50
		USB\COMPAT_VID_25FB&Class_08&SubClass_06
		USB\COMPAT_VID_25FB&Class_08
		USB\Class_08&SubClass_06&Prot_50
		USB\Class_08&SubClass_06
		USB\Class_08
		
		

Location Information:	
		Port_#0001.Hub_#0002

**Comment by ian-morgan99** [comment]
If I plug the K1ii in PcP mode, I get different answers:

A new external device was recognized by the system.

Subject:
	Security ID:		SYSTEM
	Account Name:		DESKTOP-$
	Account Domain:		WORKGROUP
	Logon ID:		0x3E7

Device ID:	USB\VID_25FB&PID_0183\7371227

Device Name:	PENTAX K-1 Mark II

Class ID:		{eec5ad98-8080-425f-922a-dabf3de3f69a}

Class Name:	WPD

Vendor IDs:	
		USB\VID_25FB&PID_0183&REV_0102
		USB\VID_25FB&PID_0183
		
		

Compatible IDs:	
		USB\COMPAT_VID_25FB&Class_06&SubClass_01&Prot_01
		USB\COMPAT_VID_25FB&Class_06&SubClass_01
		USB\COMPAT_VID_25FB&Class_06
		USB\Class_06&SubClass_01&Prot_01
		USB\Class_06&SubClass_01
		USB\Class_06
		
		

Location Information:	
		Port_#0001.Hub_#0002

**Comment by ian-morgan99** [comment]
OK. Im summary: Having done those, I think I now understand what you actually needed: [msmeissn](https://github.com/msmeissn)

For the K3iii in MSC mode:
USB\VID_25FB&PID_0189\8093033

For the K1ii in MSC mode:
USB\VID_25FB&PID_0183\7371227
For the K1ii in PcP mode:
USB\VID_25FB&PID_0182\7371227


Please let me know if that's now what you needed. (I think what you actually need is probably in the thread above, if not)

**Comment by ian-morgan99** [comment]
I don't think there's much point putting the details of the K3iii in CD-Rom mode, as I think that's only used for software installation.
