### ISSUE TITLE
k10d only gets 288 bytes status?

### ISSUE THREAD

**Issue by msmeissn** [asalamon74/pktriggercord#23]
I bought a K10D and it reports only 288 byte status, instead of 392 bytes.

I adjusted the table, but the ipslr_status_parse_k10d function seems to parse more than 288 bytes?

**Comment by msmeissn** [comment]
./pktriggercord-cli --debug --status_hex > k10d.log

[k10d.txt](https://github.com/asalamon74/pktriggercord/files/873576/k10d.txt)

**Comment by asalamon74** [comment]
I'm quite sure that 392 is the correct number. Several users reported that pktriggercord handles K10D correctly and the parse function also requires more that 288 bytes.

The official [Pentax Remote Assistant 3](http://www.ricoh-imaging.co.jp/english/support/digital/remoteassistant_k10d_mac.html) requires firmware version 1.20 or later.

What is your firmware version? I've just commited a new feature pktriggercord-cli --read_firmware_version might work for K10D and print out the firmware version. Can you upgrade to 1.20 or later?

Someone already reported this error two years ago, I suggested firmware upgrade but got no response.

**Comment by msmeissn** [comment]
yeah, i just bought it used and did not update the firmware (yet).

Firmware version: 1.00.00.07

**Comment by msmeissn** [comment]
I updated the firmware to 1.31.00.19 now and the size is now 392 bytes

**Comment by asalamon74** [comment]
I've added this info to the webpage and to README.md
Thanks for testing.
