### ISSUE TITLE
Issue with my K-3II

### ISSUE THREAD

**Issue by Nats-ji** [asalamon74/pktriggercord#33]
It appears to me that I can't set the ISO on my K-3II.
The camera was set in bulb mode. When I used `pktriggercord-cli -i 100 -t 1 -o test-1 --file_format=dng --debug`, the output file was on ISO1600.
[debug-1.log](https://github.com/asalamon74/pktriggercord/files/1936839/debug-1.log)

And when I used `pktriggercord-cli -i 800 -t 1 -o test-2 --file_format=dng --debug`, the output file was still on ISO 1600.
[debug-2.log](https://github.com/asalamon74/pktriggercord/files/1936840/debug-2.log)

One thing I noticed is that when I set the ISO, the top screen on the camera actually displays the ISO I set at, but the back screen still shows ISO1600.

**Comment by asalamon74** [comment]
It is strange, because after changing the ISO the status buffer shows the new value.

What happens if you try to specify an ISO interval using -i 800-1600? Or even -i 800-800
