### ISSUE TITLE
Trouble Installing

### ISSUE THREAD

**Issue by LucasFarmer** [asalamon74/pktriggercord#64]
whenever I try to use Make - Make clean - make install, I get this error.
~/pktriggercord-0.85.00$ sudo make && make
[sudo] password for *******         
cc -O3 -g -Wall -Isrc/external/js0n -fPIC -c src/external/js0n/js0n.c -o src/external/js0n/js0n.o
src/external/js0n/js0n.c:4:10: fatal error: string.h: No such file or directory
    4 | #include <string.h> // one strncmp() is used to do key comparison, and a strlen(key) if no len passed in
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:70: src/external/js0n/js0n.o] Error 1

Note that I am pretty new to linux, on mint 20 cinnamon.

**Comment by asalamon74** [comment]
If you want to compile the program you need several devel packages installed on the system. For `string.h` you most likely need kernel devel packages. In my repository the package is called `kernel-desktop-devel` I think in Mint it's called `linux-headers`.

Side node: For compilation, you don't need sudo, as long as you created the directory using a non-root user.
