### ISSUE TITLE
RICOH Camera USB SDK for C++

### ISSUE THREAD

**Issue by FAb7D** [asalamon74/pktriggercord#79]
I like to know your opinion as programmers regarding the usefulness of these SDKs released by Pentax and their possibility of being implemented in programs like pktriggercord.
https://api.ricoh/docs/camera-usb-sdk-cpp/
I ask why it seemed useful to me, but it doesn't seem to me that it has been used by anyone (pktriggercor, libgphoto2) and then I was curious to understand what escapes me and  why it has  not been used. Is it because the SDK  is not open source? Are not the other information useful anyway?

**Comment by asalamon74** [comment]
Yes, I've heard about that, but I don't think that I'll have time to investigate it.

**Comment by FAb7D** [comment]
Okay, thanks for the reply.
